/* all shapes:
- share a width of 300 and a hieght of 200 
- need a text property
- need a text color property
- need a shape color property
*/

class Shape {

    constructor(text, textColor, shapeColor) {
        this.text = text;
        this.textColor = textColor;
        this.shapeColor = shapeColor;
    }

    setDimensions() {
        this.width = 300;
        this.height = 200;
    }

    renderShape() {}

    renderTextEl() {
        return `
        <text x="150" y="105" text-anchor="middle" style="dominant-baseline:middle;font:74px serif;fill:${this.textColor}">
            ${this.text}
        </text>`;
    }

    render() {
        return (`<?xml version="1.0" encoding="utf-8"?>
        <!-- Autogenerated -->` + `\n` + `<svg width="300" height="200">
        ${this.renderShape()} 
        ${this.renderTextEl()}` + `\n` + `</svg>`);
    }

}

module.exports = Shape;